"use client";

import { useCallback, useState } from "react";
import { toast } from "sonner";
import type { WorkflowInstructionJobState, WorkflowInstructionTicket } from "@/core/domain/types";

interface TicketsState {
  tickets: WorkflowInstructionTicket[];
  receivers: string[];
  html?: string;
}

/**
 * Owns the tickets/receivers/html generated by a completed workflow-instruction job, plus the
 * local (unsaved) edits a PM makes to them before sending. Split out of
 * `workflow-instructions-page.tsx` once that page grew past a plain upload form — the upload
 * form's own state/handlers stay in the page, this hook only covers what happens to a job's
 * result once it lands.
 *
 * This state is intentionally ephemeral and client-only: it mirrors the in-memory, 30-minute-TTL
 * job store on the server (`core/workflow-instructions/workflow-instructions-jobs.ts`), so a page
 * refresh losing it is expected and accepted, not a bug to fix here. There is no persistence
 * layer and no corresponding "save" endpoint, which is also why this hook is plain `useState`
 * rather than built on `useApiQuery`/`useApiMutation` (`core/api/`) — those wrap server
 * round-trips, and there isn't one to wrap for this data.
 */
export function useWorkflowInstructionTickets() {
  const [state, setState] = useState<TicketsState>({ tickets: [], receivers: [] });

  /** Seeds tickets/receivers/html from a completed job's polled state. Ignores incomplete jobs. */
  const setFromJob = useCallback((job: WorkflowInstructionJobState) => {
    if (job.status !== "completed") return;
    setState({ tickets: job.tickets ?? [], receivers: job.receivers ?? [], html: job.html });
  }, []);

  /** Applies a local edit to one ticket. Never touches the server — see the module doc comment. */
  const updateTicket = useCallback((index: number, patch: Partial<WorkflowInstructionTicket>) => {
    setState((prev) => ({
      ...prev,
      tickets: prev.tickets.map((ticket, i) => (i === index ? { ...ticket, ...patch } : ticket)),
    }));
  }, []);

  /**
   * Placeholder for the future "submit the whole (edited) ticket list by email" action. The user
   * reviews/edits tickets individually first, then submits all of them at once from the list —
   * there is no per-ticket send. No email API exists yet, so this only surfaces a toast so the UI
   * flow is complete; swapping in the real request later only touches this one function.
   */
  const submitTickets = useCallback(() => {
    if (state.tickets.length === 0) return;
    toast.info(`Email sending isn't implemented yet (would send ${state.tickets.length} ticket(s))`);
  }, [state.tickets]);

  return { ...state, setFromJob, updateTicket, submitTickets };
}
