export type WorkPackageStatus =
  | "New"
  | "In progress"
  | "On hold"
  | "Closed";
export type WorkPackagePriority = "Low" | "Normal" | "High" | "Immediate";

export interface WorkPackage {
  id: number;
  subject: string;
  type: string;
  status: WorkPackageStatus;
  statusLabel?: string; // exact status title returned by OpenProject
  priority: WorkPackagePriority;
  priorityLabel?: string; // exact priority title returned by OpenProject
  project: string;
  projectId?: number; // extracted from OpenProject's `_links.project.href`
  parentId?: number; // extracted from OpenProject's `_links.parent.href`
  parentTitle?: string; // OpenProject's `_links.parent.title`
  assignee: string;
  author: string;
  createdAt: string; // ISO date
  updatedAt: string; // ISO date
  closedAt?: string; // ISO date, present if status is Closed
  startDate?: string; // yyyy-MM-dd, from OpenProject's `startDate`
  derivedDueDate?: string; //yyyy-MM-dd, from OpenProject's `startDate`
  dueDate?: string; //yyyy-MM-dd, from OpenProject's `startDate`
  customField25?: string; //yyyy-MM-dd, from OpenProject's `releaseDevDate`
  percentDone: number; // 0-100
  spentHours?: number; // total logged time in hours, from OpenProject's `spentTime` duration
}

export type Period = "week" | "month" | "quarter";

export interface TrendPoint {
  label: string;
  periodStart: string; // ISO date
  completed: number;
}

export interface StatusBreakdown {
  status: string;
  count: number;
}

export interface TypeBreakdown {
  type: string;
  count: number;
}

export interface DailyTypeTrendPoint {
  label: string; // e.g. "7/24"
  date: string; // ISO date, start of day (UTC)
  byType: Record<string, number>; // tickets created that day, keyed by type
}

export interface TypeThroughput {
  type: string;
  created: number; // tickets of this type created within the selected period
  completed: number; // tickets of this type completed within the selected period
}

export interface BurnupPoint {
  label: string; // e.g. "7/24"
  date: string; // ISO date, start of day (UTC)
  completed: number; // cumulative Task/Bug tickets done as of this day
  total: number; // cumulative Task/Bug tickets in scope (created) as of this day
}

export interface CfdPoint {
  label: string; // e.g. "7/24"
  date: string; // ISO date, start of day (UTC)
  backlog: number; // cumulative Task/Bug tickets not yet started
  inProgress: number; // cumulative Task/Bug tickets in progress or on hold
  done: number; // cumulative Task/Bug tickets completed as of this day
}

export interface WorkloadEntry {
  key: string; // assignee, priority, or project name
  count: number;
}

export interface DashboardStats {
  completedThisWeek: number;
  completedThisMonth: number;
  completedThisQuarter: number;
  openCount: number;
  trend: TrendPoint[];
  statusBreakdown: StatusBreakdown[];
  recent: WorkPackage[];
}

export type WorkloadGroupBy = "assignee" | "priority" | "project";

/**
 * Trimmed-down view of OpenProject's `UserModel` (see spec.json.json →
 * components.schemas.UserModel). Only the fields OpenLens actually reads.
 */
export interface OpenProjectUser {
  id: number;
  name: string;
  login: string;
  firstName: string;
  lastName: string;
  email: string | null;
  avatar: string | null;
  status: string;
  admin: boolean;
}

/**
 * Trimmed-down view of OpenProject's `ProjectModel` (see spec.json.json →
 * components.schemas.ProjectModel).
 */
export interface OpenProjectProjectSummary {
  id: number;
  identifier: string;
  name: string;
  active: boolean;
}

/** Response shape of `GET /api/settings` — shared between any page that needs to
 * know the connection state (Settings page, Projects page, ...). */
export interface OpenProjectSettings {
  hasCredentials: boolean;
  instanceUrl: string | null;
  useDummyData: boolean;
}

/**
 * Trimmed-down view of OpenProject's `StatusModel` (see spec.json.json →
 * components.schemas.StatusModel).
 */
export interface OpenProjectStatus {
  id: number;
  name: string;
  isClosed: boolean;
  color: string | null;
  isDefault: boolean;
  position: number;
  legacy_id?: number;
}

/** Result of submitting a workflow instruction to the configured Make.com webhook. */
export interface WorkflowInstructionSubmission {
  ok: boolean;
  status: number; // HTTP status returned by the Make.com webhook
  jobId: string; // correlates this submission with its `/callback` completion signal
}

/** Lifecycle of a workflow-instruction job, tracked until the Make.com scenario calls `/callback`. */
export type WorkflowInstructionJobStatus = "pending" | "completed" | "error";

/** A single actionable ticket generated by the Make.com scenario from a meeting transcript. */
export interface WorkflowInstructionTicket {
  title: string; // "[TEAM] [PROJECT] | Short title"
  description: string;
  solution: string;
  assignedTo: string;
  deadline: string;
}

/** Polled shape of `GET /api/workflow-instructions/callback?jobId=...`. */
export interface WorkflowInstructionJobState {
  status: WorkflowInstructionJobStatus;
  message?: string;
  html?: string;
  tickets?: WorkflowInstructionTicket[];
  receivers?: string[];
}
